endpoints:
  metrics:
    enabled: true
    sensitive: false

vcap:
  application:
    name: unknown
    cf-api: http://example.com
    space-id: unknown

logmon:
  anomalies:
    sample-size: 5
  auth:
    password: password
    username: admin
  consumption:
    password: unknown
    post-production-wait-time-millis: 10000
    username: nope@nope.com
  production:
    log-cycles: 1000
    log-byte-size: 256
    log-duration-millis: 1000
    initial-delay-millis: 10000
  time-between-tests-millis: 60000

---

spring:
  profiles: dev
  thymeleaf:
    cache: false

vcap:
  application:
    name: cf-logmon
    cf-api: https://api.run.pez.pivotal.io
    space-id: 92340jkjd09j293ej

cf:
  username: ttaylor+cf-logmon@pivotal.io
  password: FAIL
